# Copyright (c) 2026 Simon Peter
#
# SPDX-License-Identifier: BSD-2-Clause

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = gallery
gallery_OBJC_FILES = gallery.m
gallery_PRINCIPAL_CLASS = NSApplication

include $(GNUSTEP_MAKEFILES)/application.make
