include $(GNUSTEP_MAKEFILES)/common.make

TEST_TOOL_NAME = t_GeorgePlatinum t_GeorgeTitleBar

ADDITIONAL_CPPFLAGS += -I$(GNUSTEP_MAKEFILES)/TestFramework

t_GeorgePlatinum_OBJC_FILES = t_GeorgePlatinum.m
t_GeorgeTitleBar_OBJC_FILES = t_GeorgeTitleBar.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make
